create table if not exists growup_snapshots (
  id bigint generated by default as identity primary key,
  user_id text,
  app_state jsonb,
  state jsonb,
  created_at timestamp with time zone default now()
);

alter table growup_snapshots enable row level security;

create policy if not exists "Anyone can insert growup snapshots"
on growup_snapshots
for insert
to anon
with check (true);

create policy if not exists "Anyone can read growup snapshots"
on growup_snapshots
for select
to anon
using (true);
