create table if not exists growup_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid,
  app_state jsonb,
  state jsonb,
  created_at timestamp with time zone default now()
);

alter table growup_snapshots enable row level security;

drop policy if exists "Anyone can insert growup snapshots" on growup_snapshots;
drop policy if exists "Anyone can read growup snapshots" on growup_snapshots;
drop policy if exists "Users can insert own growup snapshots" on growup_snapshots;
drop policy if exists "Users can read own growup snapshots" on growup_snapshots;

create policy "Users can insert own growup snapshots"
on growup_snapshots
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can read own growup snapshots"
on growup_snapshots
for select
to authenticated
using (auth.uid() = user_id);
